### ISSUE TITLE
Advanced OOD CSS Customization

### ISSUE THREAD

**Issue by brandonbiggs** [OSC/ood-documentation#1133]
There was a slack discussion about how to further customize OOD with themes. There is some documentation on how to add your own CSS - https://osc.github.io/ood-documentation/latest/customizations.html#custom-css-files but there aren't examples. Alan asked on Slack for me to create this issue to track potentially adding some CSS examples.

Here is my current CSS customization to make multiple aspects of OOD line up with our institute's branding.
```css
/* Our brand blue */
.btn-primary {
  background-color: #05509F;
  border-color: #05509F;
}

.apps-section-header-blue {
  background-color: #05509F;
}

.app-launcher .launcher-click {
  border: 4px solid #05509F;
}

.system-and-shared-apps-header {
  background-color: #05509F;
}

.list-group-item.active {
  background-color: #2BA8E0;
  border-color: #2BA8E0;
}

.alert-success {
    color: white;
    background-color: #07519E;
    border-color: #07519E;
}

.alert-info {
    color: white;
    background-color: #2BA8E0;
    border-color: #2BA8E0;
}

.btn-danger {
    background-color: #CF1E4C;
    border-color: #CF1E4C;
}

.badge-success {
    color: black;
    background-color: #8DC340;
}
```
