### ISSUE TITLE
Document Schema Cluster ACL Feature

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/ood-documentation#135]
At OSC we block users from accessing certain queues / clusters via an ACL. This is currently an undocumented feature at the cluster config schema.

``` 
acls:
    - adapter: "group"
      groups:
        - "ruby"
      type: "whitelist"
```
