### ISSUE TITLE
Github action: update PR description with link to ood-documentation-test

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-documentation#516]
When a new PR is added, a github action should run that checks the description and if the string 

`https://osc.github.io/ood-documentation-test/BRANCH-NAME` is found, replace `BRANCH-NAME` with the branch name

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737413451191) by [Unito](https://www.unito.io)

**Comment by msquee** [comment]
@ChissCake 

To detect a new pull request in GitHub actions:
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request

A good resource to look at is the Document Merge action that we use:
```yaml
name: Create Document issue for Merge Request

# Run this action when we merge into master
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  # Create an issue on the documentation repository to document whatever was just pulled in.
  create-doc-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Create an issue on the documentation repository
        if: contains(github.event.pull_request.labels.*.name, 'needs doc')
        run: |
          PR_NUM=${{ github.event.pull_request.number }}
          TITLE="${{ github.event.pull_request.title }}"
          BODY="{
             \"title\": \"$TITLE\",
             \"body\": \"Create documentation for https://github.com/OSC/ondemand/pull/$PR_NUM\"
          }"

          curl --silent --output /dev/null --request POST \
          --url https://api.github.com/repos/OSC/ood-documentation/issues \
          --header 'Authorization: token ${{ secrets.OSCWIAG_ISSUE_TOKEN }}' \
          --header 'content-type: application/json' \
          --data "$BODY"
 ```

This is the money right here:
`if: contains(github.event.pull_request.labels.*.name, 'needs doc')`
