### ISSUE TITLE
Document K8 ondemand web host requirements

### ISSUE THREAD

**Issue by treydock** [OSC/ood-documentation#556]
Need to document need valid kubectl and kube config on ondemand web host. The kube config must be setup with token from this service account: https://github.com/OSC/ondemand/blob/35932d4f778030b03b64629e02053647d5c688b6/hooks/k8s-bootstrap/ondemand.yaml#L54-L58

Example of extracting service account token (pulled from OSC wiki):

```
TOKEN=$(kubectl describe serviceaccount ondemand -n ondemand | grep Tokens | awk '{ print $2 }')
kubectl describe secret $TOKEN -n ondemand | grep "token:"
```

Full kube config that needs to be in root's home directory on ondemand node:

```yaml
---
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: PATH-TO-CA-CERT
    server: https://REPLACE:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: ondemand
  name: ondemand@kubernetes
current-context: ondemand@kubernetes
preferences: {}
users:
- name: ondemand
  user:
    token: OMIT
```

Can also replace `certificate-authority` with `certificate-authority-data` that is base64 encoded CA certificate.
