### ISSUE TITLE
Example incorrectly swapped first and last "options" element(?)

### ISSUE THREAD

**Issue by HenrikBengtsson** [OSC/ood-documentation#674]
On <https://osc.github.io/ood-documentation/latest/app-development/interactive/form.html?highlight=form%20yml>, Section 'options (Array<Array<String>>, null)' has an example:

```yaml
options:
  - ["Volvo", "volvo"]
  - ["Ford", "ford"]
  - ["Toyota", "toyota"]
```

which is explained as:

"Typically the options are given as a list of pairs. The first string in the pair is the option text and the second string in the pair is the option value.

The user will see a list of options “Volvo”, “Ford”, and “Toyota” to choose from in the HTML form, but the backend will process a value of either “volvo”, “ford”, or “toyota” depending on what the user chose."

If so, the example in <https://osc.github.io/ood-documentation/latest/app-development/interactive/form.html?highlight=form%20yml#configuring-which-cluster-to-submit-to> seems to be swapped;

```yml
# ${HOME}/ondemand/dev/different_select_cluster/form.yml
---
form:
  - cluster
attributes:
  cluster:
    widget: "select"
    options:
      - ["cluster1", "The first cluster"]
      - ["cluster2", "The second cluster"]
```

If the above explanation is correct, shouldn't the latter be:

```yml
    options:
      - ["The first cluster", "cluster1"]
      - ["The second cluster", "cluster2"]
```

?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202221504516333) by [Unito](https://www.unito.io)
