### ISSUE TITLE
\n not working in 3.1

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood-documentation#864]
It may be due to the ruby upgrade - but things like this will not work in the next release. 

https://github.com/OSC/ood-documentation/blob/5edc35056d03ddaf4bc1f5b126c94784d983170e/source/installation/cluster-config-schema.rst?plain=1#L51-L54

We need to update documentation to use multiline strings like this (and likely add a breaking change to the 3.1 release notes).

```yaml
    batch_connect:
        basic:
          script_wrapper: |
           module restore
           %s
        vnc:
          script_wrapper: |
            module restore
            module load ondemand-vnc
            %s
```
